### PR TITLE
Implement docker archetype

### PR DESCRIPTION
**Pull request by bricerisingalgorand**
This is basically a copy of the npm archetype, but using git hashes for versioning. This allows the archetype to just generally build/deploy any dockerfile without dependencies on npm

### CODE REVIEW

**Comment by algobarb** [comment]
how might this change affect older implementations using mule?

**Comment by bricerisingalgorand** [comment]
> how might this change affect older implementations using mule?

It shouldn't have any impact, all `search_parent_directories=True` does is tell the library to keep checking parent dirs until it finds the root dir of the git repo

**Comment by algobarb** [comment]
The other PR helped me understand how we would explicitly call the archetype now. Do you mind documenting the archetypes detail somewhere in this repo for future reference?

**Review by algobarb — DISMISSED** [review]
Thanks this looks good!

**Review by egieseke — APPROVED** [review]

**Review by algobarb — APPROVED** [review]

**Pull request merged**
